export const NIGERIAN_BANKS = [
  // Commercial banks
  ["Access Bank", "Commercial bank", "#F58220"],
  ["Citibank Nigeria", "Commercial bank", "#056DAE"],
  ["Ecobank Nigeria", "Commercial bank", "#146A45"],
  ["Fidelity Bank", "Commercial bank", "#207E39"],
  ["First Bank of Nigeria", "Commercial bank", "#12458B"],
  ["First City Monument Bank (FCMB)", "Commercial bank", "#6C3C90"],
  ["Globus Bank", "Commercial bank", "#006D76"],
  ["Guaranty Trust Bank (GTBank)", "Commercial bank", "#E85A13"],
  ["Keystone Bank", "Commercial bank", "#0B6A8D"],
  ["Nova Bank", "Commercial bank", "#263B85"],
  ["Optimus Bank", "Commercial bank", "#103B78"],
  ["Parallex Bank", "Commercial bank", "#1E5595"],
  ["Polaris Bank", "Commercial bank", "#234AA2"],
  ["PremiumTrust Bank", "Commercial bank", "#0B6779"],
  ["Providus Bank", "Commercial bank", "#5E428A"],
  ["Signature Bank", "Commercial bank", "#295C8C"],
  ["Stanbic IBTC Bank", "Commercial bank", "#125DAA"],
  ["Standard Chartered Bank Nigeria", "Commercial bank", "#138E7A"],
  ["Sterling Bank", "Commercial bank", "#C9212C"],
  ["SunTrust Bank", "Commercial bank", "#DF8D21"],
  ["Titan Trust Bank", "Commercial bank", "#174C77"],
  ["Union Bank of Nigeria", "Commercial bank", "#1484BA"],
  ["United Bank for Africa (UBA)", "Commercial bank", "#C91E2F"],
  ["Unity Bank", "Commercial bank", "#245F9C"],
  ["Wema Bank", "Commercial bank", "#8C367D"],
  ["Zenith Bank", "Commercial bank", "#C51E2D"],

  // Non-interest banks
  ["Alternative Bank", "Non-interest bank", "#147D52"],
  ["Jaiz Bank", "Non-interest bank", "#14633D"],
  ["Lotus Bank", "Non-interest bank", "#168B71"],
  ["TAJBank", "Non-interest bank", "#2B7A55"],

  // Merchant banks
  ["Coronation Merchant Bank", "Merchant bank", "#8B5D3B"],
  ["FBNQuest Merchant Bank", "Merchant bank", "#31568D"],
  ["Greenwich Merchant Bank", "Merchant bank", "#286C59"],
  ["Rand Merchant Bank Nigeria", "Merchant bank", "#42658B"],

  // Payment service banks and mobile money wallets
  ["9 Payment Service Bank (9PSB)", "Payment service bank", "#40A629"],
  ["Hope Payment Service Bank", "Payment service bank", "#1C6B48"],
  ["MoneyMaster Payment Service Bank", "Payment service bank", "#F2B705"],
  ["MoMo Payment Service Bank", "Payment service bank", "#FFCC00"],
  ["SmartCash Payment Service Bank", "Payment service bank", "#E41E2B"],
  ["Chams Mobile", "Mobile money / fintech", "#3055A4"],
  ["eTranzact PocketMoni", "Mobile money / fintech", "#0E7B45"],
  ["KongaPay", "Mobile money / fintech", "#E51A8A"],
  ["NowNow", "Mobile money / fintech", "#6BBE45"],
  ["OPay", "Mobile money / fintech", "#00B875"],
  ["Paga", "Mobile money / fintech", "#EF7D00"],
  ["PalmPay", "Mobile money / fintech", "#6D43D9"],
  ["Pocket by PiggyVest", "Mobile money / fintech", "#1B9C85"],
  ["Teasy Mobile Money", "Mobile money / fintech", "#167B55"],
  ["Xpress Wallet", "Mobile money / fintech", "#2257A6"],

  // Digital banks, finance apps and fintech wallets
  ["Carbon", "Digital finance / fintech", "#22A65A"],
  ["FairMoney", "Digital finance / fintech", "#1859C9"],
  ["Kuda Bank", "Digital bank / MFB", "#40196D"],
  ["Moniepoint", "Digital bank / MFB", "#246BFD"],
  ["Nomba", "Digital finance / fintech", "#5A35D6"],
  ["Renmoney", "Digital finance / MFB", "#F05A28"],
  ["Rubies Bank", "Digital bank / MFB", "#8C2B8F"],
  ["Sparkle", "Digital bank / MFB", "#7B2CBF"],
  ["VBank by VFD Microfinance Bank", "Digital bank / MFB", "#252B42"],
  ["Mintyn by Finex Microfinance Bank", "Digital bank / MFB", "#10A37F"],
  ["Eyowo", "Digital finance / fintech", "#7A52CC"],
  ["Branch", "Digital finance / fintech", "#00A884"],
  ["Aella Credit", "Digital finance / fintech", "#2764C8"],
  ["Cowrywise", "Digital finance / fintech", "#0066F5"],
  ["PiggyVest", "Digital finance / fintech", "#0D60D8"],
  ["Risevest", "Digital finance / fintech", "#1565C0"],
  ["Bamboo", "Digital finance / fintech", "#0E9F6E"],
  ["Chipper Cash", "Digital finance / fintech", "#6C4CF1"],
  ["Leatherback", "Digital finance / fintech", "#2E4DA7"],
  ["LemFi", "Digital finance / fintech", "#00A86B"],

  // Microfinance banks commonly used for personal and business accounts
  ["AB Microfinance Bank", "Microfinance bank", "#315C83"],
  ["Accion Microfinance Bank", "Microfinance bank", "#E16B2D"],
  ["Addosser Microfinance Bank", "Microfinance bank", "#216D60"],
  ["Advans La Fayette Microfinance Bank", "Microfinance bank", "#2B67A0"],
  ["Alert Microfinance Bank", "Microfinance bank", "#B23A48"],
  ["Amju Unique Microfinance Bank", "Microfinance bank", "#456B8C"],
  ["Baobab Microfinance Bank", "Microfinance bank", "#68A83F"],
  ["BoI Microfinance Bank", "Microfinance bank", "#327A54"],
  ["Bosak Microfinance Bank", "Microfinance bank", "#9B673E"],
  ["Bowen Microfinance Bank", "Microfinance bank", "#386E91"],
  ["CEMCS Microfinance Bank", "Microfinance bank", "#4A6F8D"],
  ["CIT Microfinance Bank", "Microfinance bank", "#365D8C"],
  ["Consumer Microfinance Bank", "Microfinance bank", "#536B89"],
  ["Credit Afrique Microfinance Bank", "Microfinance bank", "#4E718D"],
  ["Davodani Microfinance Bank", "Microfinance bank", "#486983"],
  ["EdFin Microfinance Bank", "Microfinance bank", "#2F6C78"],
  ["Empire Trust Microfinance Bank", "Microfinance bank", "#79588F"],
  ["Fina Trust Microfinance Bank", "Microfinance bank", "#486A91"],
  ["Fortis Microfinance Bank", "Microfinance bank", "#436C8A"],
  ["Grooming Microfinance Bank", "Microfinance bank", "#375F82"],
  ["Hasal Microfinance Bank", "Microfinance bank", "#436D72"],
  ["Infinity Microfinance Bank", "Microfinance bank", "#467A85"],
  ["LAPO Microfinance Bank", "Microfinance bank", "#13874B"],
  ["Letshego Microfinance Bank", "Microfinance bank", "#E67E22"],
  ["Mainstreet Microfinance Bank", "Microfinance bank", "#2C6388"],
  ["Mutual Trust Microfinance Bank", "Microfinance bank", "#526D8B"],
  ["NPF Microfinance Bank", "Microfinance bank", "#1B6D4B"],
  ["Page Financials", "Microfinance bank", "#E05B32"],
  ["Petra Microfinance Bank", "Microfinance bank", "#5D698D"],
  ["Rehoboth Microfinance Bank", "Microfinance bank", "#4B7086"],
  ["Seedvest Microfinance Bank", "Microfinance bank", "#2D8062"],
  ["Shepherd Trust Microfinance Bank", "Microfinance bank", "#596E88"],
  ["Stanford Microfinance Bank", "Microfinance bank", "#4F6687"],
  ["TrustBanc Microfinance Bank", "Microfinance bank", "#315D7B"],
  ["VFD Microfinance Bank", "Microfinance bank", "#252B42"],
  ["Verite Microfinance Bank", "Microfinance bank", "#4B6F84"],
  ["Wetland Microfinance Bank", "Microfinance bank", "#347566"],

  // Primary mortgage banks
  ["Abbey Mortgage Bank", "Mortgage bank", "#236B7C"],
  ["AG Mortgage Bank", "Mortgage bank", "#4B6288"],
  ["Brent Mortgage Bank", "Mortgage bank", "#547184"],
  ["Delta Trust Mortgage Bank", "Mortgage bank", "#607F95"],
  ["Federal Mortgage Bank of Nigeria", "Mortgage bank", "#336A92"],
  ["First Generation Mortgage Bank", "Mortgage bank", "#507690"],
  ["Gateway Mortgage Bank", "Mortgage bank", "#51738B"],
  ["Haggai Mortgage Bank", "Mortgage bank", "#586B87"],
  ["Infinity Trust Mortgage Bank", "Mortgage bank", "#3D7185"],
  ["Jubilee-Life Mortgage Bank", "Mortgage bank", "#597D8A"],
  ["Lagos Building Investment Company", "Mortgage bank", "#587C91"],
  ["LivingTrust Mortgage Bank", "Mortgage bank", "#447F78"],
  ["Mutual Alliance Mortgage Bank", "Mortgage bank", "#60718C"],
  ["Nigeria Police Mortgage Bank", "Mortgage bank", "#446B84"],
  ["Platinum Mortgage Bank", "Mortgage bank", "#4D7193"],
  ["Refuge Mortgage Bank", "Mortgage bank", "#4D7886"],
  ["Safetrust Mortgage Bank", "Mortgage bank", "#447887"],
  ["Trustbond Mortgage Bank", "Mortgage bank", "#496F8C"],
].map(([name, category, color]) => ({ name, category, color }));
